from __future__ import unicode_literals

DUTIES = {
    "Mặt trận Tổ quốc",
    "Ủy ban nhân dân",
    "Bộ Tư lệnh Bộ đội Biên phòng",
    "Bộ Tham mưu",
    "Cục Chính trị",
    "Cục Trinh sát",
    "Cục Phòng, chống ma túy và tội phạm",
    "Cục Cửa khẩu",
    "Cục Hậu cần",
    "Cục Kỹ thuật",
    "Bộ chỉ huy Bộ đội Biên phòng",
    "Phòng Tham mưu",
    "Phòng Chính trị",
    "Phòng Trinh sát",
    "Phòng Phòng, chống ma túy và tội phạm",
    "Phòng Hậu cần",
    "Phòng Kỹ thuật",
    "Đội Vũ trang",
    "Đội Vận động quần chúng",
    "Đội Trinh sát",
    "Đội Phòng, chống ma túy và tội phạm",
    "Đội Kiểm soát hành chính",
    "Đội Tham mưu - Hành chính",
    "Đội Tàu thuyền",
    "Trạm Biên phòng",
    "Ban chỉ huy Biên phòng",
    "Ban Tham mưu",
    "Ban Chính trị",
    "Ban Trinh sát",
    "Ban Phòng, chống ma túy và tội phạm",
    "Ban Hậu cần - Kỹ thuật",
    "Đội Hành chính",
    "Đội Thủ tục",
    "Đội Tuần tra biên phòng",
    "Ban Tham mưu - Đào tạo",
    "Ban Hậu cầu",
    "Phòng Đào tạo",
    "Bộ trưởng Bộ Quốc phòng",
    "Bộ Tài chính",
    "Bộ Nông nghiệp và Phát triển nông thôn",
    "Bộ Ngoại giao",
    "Tổng lãnh sự quán",
    "Tổng lãnh sự",
    "Lãnh sự quán",
    "Cơ quan đại diện",
    "văn phòng trực thuộc",
    "Bộ Công Thương",
    "Bộ Công An",
    "Bộ Nội vụ",
    "Bộ Tư pháp",
    "Bộ Kế hoạch và Đầu tư",
    "Bộ Tài chính",
    "Bộ Giao thông Vận tải",
    "Bộ Xây dựng",
    "Bộ Tài nguyên và Môi trường",
    "Bộ Thông tin và Truyền thông",
    "Bộ Lao động - Thương binh và Xã hội",
    "Bộ Văn hóa, Thể thao và Du lịch",
    "Bộ Khoa học và Công nghệ",
    "Bộ Giáo dục và Đào tạo",
    "Bộ Y tế", 
    "HĐND Thành phố",
    "HĐND Tỉnh",
    "HĐND Huyện",
    "HĐND Xã",
    "Thủ tướng Chính phủ",
    "Chủ tịch nước",
    "Tổng bí thư",
    "Phó thủ tướng",
    "Hội đồng quản trị",
    "Chủ tịch hội đồng quản trị"
    "Chủ tịch HĐND Thành phố",
    "Chủ tịch HĐND Tỉnh",
    "Chủ tịch HĐND Huyện",
    "Chủ tịch HĐND Xã",
    "Ủy ban Thường vụ Quốc hội",
    "Hội đồng Dân tộc",
    "Ủy ban Pháp luật",
    "Ủy ban Tư pháp",
    "Ủy ban Kinh tế",
    "Ủy ban Tài chính – Ngân sách",
    "Ủy ban Quốc phòng và An ninh",
    "Ủy ban Xã hội",
    "Ủy ban Đối ngoại",
    "Ủy ban Khoa học, Công nghệ và Môi trường",
    "Ủy ban Văn hóa, Giáo dục",
    "Văn phòng Quốc hội",
    "Ban Công tác đại biểu",
    "Ban Dân nguyện",
    "Viện Nghiên cứu lập pháp",
    "Kiểm toán Nhà nước",
    "Hội đồng Bầu cử Quốc gia",
    "Chủ tịch Quốc hội",
    "Phó Chủ tịch Quốc hội",
    "Chủ nhiệm Ủy ban của Quốc hội",
    "Phó Chủ nhiệm Ủy ban của Quốc hội",
    "Chủ tịch Hội đồng nhân dân",
    "Phó Chủ tịch Hội đồng nhân dân",
    "Văn phòng Trung ương Đảng",
    "Ban Tổ chức Trung ương",
    "Ban Tuyên giáo Trung ương",
    "Ban Dân vận Trung ương",
    "Ban Đối ngoại Trung ương",
    "Ban Nội chính Trung ương",
    "Ban Kinh tế Trung ương",
    "Hội đồng Lý luận Trung ương",
    "Ban Cán sự Đảng Ngoài nước",
    "Quân ủy Trung ương",
    "Đảng ủy Công an Trung ương",
    "Đảng bộ các tỉnh, thành phố",
    "Đảng ủy Khối Doanh nghiệp Trung ương",
    "Đảng ủy Khối các cơ quan Trung ương"   
}


DUTIES = {item: item.replace("-", "").replace(" ", "_") for item in DUTIES}
# DUTIES = {item.replace("-", "") for item in DUTIES}
# DUTIES = {item: item.replace(" ", "_") for item in DUTIES}