from __future__ import unicode_literals

LEGAL_DICT = {
    "luật pháp": "luật_pháp",
    "hiến pháp": "hiến_pháp",
    "tư pháp": "tư_pháp",
    "căn cứ": "căn_cứ",
    "cơ sở pháp lý": "cơ_sở_pháp_lý",
    "điều khoản": "điều_khoản",
    "hiệu lực": "hiệu_lực",
    "thẩm quyền": "thẩm_quyền",
    "ban hành": "ban_hành",
    "đình chỉ": "đình_chỉ",
    "hành chính": "hành_chính",
    "quy định": "quy_định",
    "nghị định": "nghị_định",
    "quy phạm": "quy_phạm",
    "chỉ thị": "chỉ_thị",
    "xét xử": "xét_xử",
    "bồi thường": "bồi_thường",
    "hòa giải": "hòa_giải",
    "trách nhiệm": "trách_nhiệm",
    "nghĩa vụ": "nghĩa_vụ",
    "quyền lợi": "quyền_lợi",
    "tài sản": "tài_sản",
    "hôn nhân": "hôn_nhân",
    "hợp đồng": "hợp_đồng",
    "cam kết": "cam_kết",
    "thỏa thuận": "thỏa_thuận",
    "giao dịch": "giao_dịch",
    "mua bán": "mua_bán",
    "tặng cho": "tặng_cho",
    "vay nợ": "vay_nợ",
    "thế chấp": "thế_chấp",
    "cầm cố": "cầm_cố",
    "ủy quyền": "ủy_quyền",
    "doanh nghiệp": "doanh_nghiệp",
    "công ty": "công_ty",
    "cổ phần": "cổ_phần",
    "điều lệ": "điều_lệ",
    "giấy phép": "giấy_phép",
    "đăng ký": "đăng_ký",
    "pháp nhân": "pháp_nhân",
    "vi phạm pháp luật": "vi_phạm_pháp_luật",
    "bồi thường thiệt hại": "bồi_thường_thiệt_hại",
    "thi hành án": "thi_hành_án",
    "tự do ngôn luận": "tự_do_ngôn_luận",
    "pháp lý": "pháp_lý",
    "tài sản thế chấp": "tài_sản_thế_chấp",
    "tài sản đảm bảo": "tài_sản_đảm_bảo",
    "chuyển nhượng đất đai": "chuyển_nhượng_đất_đai",
    "quyền sở hữu": "quyền_sở_hữu",
    "trách nhiệm hữu hạn": "trách_nhiệm_hữu_hạn",
    "chế tài hành chính": "chế_tài_hành_chính",
    "quyền lợi người lao động": "quyền_lợi_người_lao_động",
    "biện pháp cưỡng chế": "biện_pháp_cưỡng_chế",
    "tố tụng hình sự": "tố_tụng_hình_sự",
    "vi phạm hành chính": "vi_phạm_hành_chính",
    "quy chế hoạt động": "quy_chế_hoạt_động",
    "hợp đồng lao động": "hợp_đồng_lao_động",
    "tập trung dân chủ": "tập_trung_dân_chủ",
    "hợp đồng dân sự": "hợp_đồng_dân_sự",
    "hành lang pháp lý": "hành_lang_pháp_lý",
    "tuyên giáo trung ương": "tuyên_giáo_trung_ương",
    "chứng minh nhân dân": "chứng_minh_nhân_dân",
    "biên bản vi phạm": "biên_bản_vi_phạm",
    "luật doanh nghiệp": "luật_doanh_nghiệp",
    "đăng ký kinh doanh": "đăng_ký_kinh_doanh",
    "bảo hiểm xã hội": "bảo_hiểm_xã_hội",
    "bảo hiểm nhân thọ": "bảo_hiểm_nhân_thọ",
    "bảo hiểm hưu trí": "bảo_hiểm_hưu_trí",
    "bảo hiểm tử kỳ": "bảo_hiểm_tử_kỳ",
    "bảo hiểm vi mô": "bảo_hiểm_vi_mô",
    "tội phạm ma túy": "tội_phạm_ma_túy",
    "bảo lãnh ngân hàng": "bảo_lãnh_ngân_hàng",
    "báo cáo tài chính": "báo_cáo_tài_chính",
    "an ninh mạng": "an_ninh_mạng",
    "vốn đầu tư": "vốn_đầu_tư",
    "mẫu biểu": "mẫu_biểu",
    "kế toán thuế": "kế_toán_thuế",
    "hộ gia đình": "hộ_gia_đình",
    "tái đầu tư": "tái_đầu_tư",
    "tàng trữ trái phép": "tàng_trữ_trái_phép",
    "văn hóa phẩm đồi trụy": "văn_hóa_phẩm_đồi_trụy",
    "tòa án nhân dân": "tòa_án_nhân_dân",
    "báo động lũ": "báo_động_lũ",
    "bổ sung": "bổ_sung",
    "thay thế": "thay_thế",
    "gia hạn": "gia_hạn",
    "tước quyền": "tước_quyền",
    "tịch thu": "tịch_thu",
    "cảnh cáo": "cảnh_cáo",
    "phạt nguội": "phạt_nguội",
    "kê khai": "kê_khai",
    "chứng từ": "chứng_từ",
    "thủ tục": "thủ_tục",
    "biên bản": "biên_bản",
    "báo cáo": "báo_cáo",
    "cá nhân": "cá_nhân",
    "tổ chức": "tổ_chức",
    "tiêu chí": "tiêu_chí",
    'nguyên tắc': 'nguyên_tắc',
    'kỳ hạn': "kỳ hạn",
    "tờ trình": "tờ_trình",
    "tường trình": "tường_trình",
    "bổn_phận": "bổn_phận",
    "đảm bảo": "đảm_bảo",
    "hạn mức": "hạn_mức",
    "hạn định": "hạn_định",
    "gia hạn": "gia_hạn",
    "hết hạn": "hết_hạn",
    "phi chính phủ": "phi_chính_phủ",
    "phi lợi nhuận": "phi_lợi_nhuận",
    'bình đẳng giới': 'bình_đẳng_giới',
}

